name = "mysig"
version = "0.1.1"
target = "javascript"

description = "Tookit for building web (sites, apps or pages) with Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "mysig" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
snag = ">= 0.3.0 and < 1.0.0"
plinth = ">= 0.5.0 and < 1.0.0"
gleam_javascript = ">= 0.13.0 and < 1.0.0"
gleam_http = ">= 3.7.0 and < 4.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
lustre = ">= 4.6.2 and < 5.0.0"
javascript_mutable_reference = ">= 1.0.0 and < 2.0.0"
marceau = ">= 1.3.0 and < 2.0.0"
midas = ">= 1.2.0 and < 2.0.0"
midas_node = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
